
image:
  file: .gitpod.Dockerfile
ports:
  - port: 3000
    onOpen: ignore
  - port: 6881
    onOpen: ignore
  - port: 6891
    onOpen: ignore
  - port: 51231
    onOpen: ignore
tasks:
  - init: python3 main.py
    name: Split terminal
